// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TP4SCS.Library.Models.Data;

#nullable disable

namespace TP4SCS.Library.Migrations
{
    [DbContext(typeof(Tp4scsDevDatabaseContext))]
    [Migration("20241026134127_InitialDB")]
    partial class InitialDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TP4SCS.Library.Models.Data.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Dob")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Fcmtoken")
                        .HasColumnType("text")
                        .HasColumnName("FCMToken");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsGoogle")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__Account__3214EC07D2F2871B");

                    b.HasIndex(new[] { "Phone" }, "UQ__Account__5C7E359E71751182")
                        .IsUnique();

                    b.HasIndex(new[] { "Email" }, "UQ__Account__A9D105347F159896")
                        .IsUnique();

                    b.ToTable("Account", (string)null);
                });

            modelBuilder.Entity("TP4SCS.Library.Models.Data.AccountAddress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Ward")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__AccountA__3214EC07D8D8ABB7");

                    b.HasIndex("AccountId");

                    b.ToTable("AccountAddress", (string)null);
                });

            modelBuilder.Entity("TP4SCS.Library.Models.Data.AssetUrl", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BusinessId")
                        .HasColumnType("int");

                    b.Property<int?>("FeedbackId")
                        .HasColumnType("int");

                    b.Property<bool>("IsImage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int?>("ServiceId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id")
                        .HasName("PK__AssetURL__3214EC07292B8E5F");

                    b.HasIndex("BusinessId");

                    b.HasIndex("FeedbackId");

                    b.HasIndex("ServiceId");

                    b.ToTable("AssetURL", (string)null);
                });

            modelBuilder.Entity("TP4SCS.Library.Models.Data.BusinessBranch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("BusinessId")
                        .HasColumnType("int");

                    b.Property<int>("CanceledAmount")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EmployeeIds")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("FinishedAmount")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeliverySupport")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PendingAmount")
                        .HasColumnType("int");

                    b.Property<int>("ProcessingAmount")
                        .HasColumnType("int");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Ward")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__Business__3214EC07BAA71D9F");

                    b.HasIndex("BusinessId");

                    b.ToTable("BusinessBranch", (string)null);
                });

            modelBuilder.Entity("TP4SCS.Library.Models.Data.BusinessProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CanceledAmount")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExpiredTime")
                        .HasColumnType("datetime");

                    b.Property<int>("FinishedAmount")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.Property<int>("PendingAmount")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<int>("ProcessingAmount")
                        .HasColumnType("int");

                    b.Property<int>("Rank")
                        .HasColumnType("int");

                    b.Property<decimal>("Rating")
                        .HasColumnType("decimal(3, 1)");

                    b.Property<DateTime>("RegisteredTime")
                        .HasColumnType("datetime");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("TotalOrder")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Business__3214EC07B9CD4797");

                    b.HasIndex(new[] { "Phone" }, "UQ__Business__5C7E359E40D15ED5")
                        .IsUnique();

                    b.HasIndex(new[] { "Name" }, "UQ__Business__737584F65C16A395")
                        .IsUnique();

                    b.HasIndex(new[] { "OwnerId" }, "UQ__Business__819385B9D1697A93")
                        .IsUnique();

                    b.ToTable("BusinessProfile", (string)null);
                });

            modelBuilder.Entity("TP4SCS.Library.Models.Data.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("Id")
                        .HasName("PK__Cart__3214EC07AAB9F8B2");

                    b.HasIndex(new[] { "AccountId" }, "UQ__Cart__349DA5A7E55EE33F")
                        .IsUnique();

                    b.ToTable("Cart", (string)null);
                });

            modelBuilder.Entity("TP4SCS.Library.Models.Data.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<int?>("MaterialId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__CartItem__3214EC07791337C2");

                    b.HasIndex("CartId");

                    b.HasIndex("MaterialId");

                    b.HasIndex("ServiceId");

                    b.ToTable("CartItem", (string)null);
                });

            modelBuilder.Entity("TP4SCS.Library.Models.Data.Feedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderItemId")
                        .HasColumnType("int");

                    b.Property<decimal>("Rating")
                        .HasColumnType("decimal(3, 1)");

                    b.HasKey("Id")
                        .HasName("PK__Feedback__3214EC07E5213B77");

                    b.HasIndex("OrderItemId");

                    b.ToTable("Feedback", (string)null);
                });

            modelBuilder.Entity("TP4SCS.Library.Models.Data.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Storage")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Material__3214EC07DDCC2B47");

                    b.ToTable("Material", (string)null);
                });

            modelBuilder.Entity("TP4SCS.Library.Models.Data.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<int?>("AddressId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime");

                    b.Property<decimal>("DeliveredFee")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<DateTime?>("DeliveredTime")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsAutoReject")
                        .HasColumnType("bit");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("OrderPrice")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("ShippingCode")
                        .HasColumnType("text");

                    b.Property<string>("ShippingUnit")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("Id")
                        .HasName("PK__Order__3214EC07D3BA8734");

                    b.HasIndex("AccountId");

                    b.HasIndex("AddressId");

                    b.ToTable("Order", (string)null);
                });

            modelBuilder.Entity("TP4SCS.Library.Models.Data.OrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("MaterialId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__OrderDet__3214EC07114169AF");

                    b.HasIndex("MaterialId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ServiceId");

                    b.ToTable("OrderDetail", (string)null);
                });

            modelBuilder.Entity("TP4SCS.Library.Models.Data.OrderNotification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NotificationTime")
                        .HasColumnType("datetime");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__OrderNot__3214EC0764990903");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderNotification", (string)null);
                });

            modelBuilder.Entity("TP4SCS.Library.Models.Data.PaymentMethod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__PaymentM__3214EC072F62BE42");

                    b.HasIndex(new[] { "Name" }, "UQ__PaymentM__737584F6FA15D1A7")
                        .IsUnique();

                    b.ToTable("PaymentMethod", (string)null);
                });

            modelBuilder.Entity("TP4SCS.Library.Models.Data.Promotion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("NewPrice")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("SaleOff")
                        .HasColumnType("int");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__Promotio__3214EC0745F5DF31");

                    b.HasIndex(new[] { "ServiceId" }, "UQ__Promotio__C51BB00B8A38A700")
                        .IsUnique();

                    b.ToTable("Promotion", (string)null);
                });

            modelBuilder.Entity("TP4SCS.Library.Models.Data.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FeedbackedNum")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("OrderedNum")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal>("Rating")
                        .HasColumnType("decimal(3, 1)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__Service__3214EC072B056EB1");

                    b.HasIndex("BranchId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Service", (string)null);
                });

            modelBuilder.Entity("TP4SCS.Library.Models.Data.ServiceCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__ServiceC__3214EC074F5D6087");

                    b.HasIndex(new[] { "Name" }, "UQ__ServiceC__737584F60D748FEF")
                        .IsUnique();

                    b.ToTable("ServiceCategory", (string)null);
                });

            modelBuilder.Entity("TP4SCS.Library.Models.Data.ServiceMaterial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("MaterialId")
                        .HasColumnType("int");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__ServiceM__3214EC077BF357C1");

                    b.HasIndex("MaterialId");

                    b.HasIndex("ServiceId");

                    b.ToTable("ServiceMaterial", (string)null);
                });

            modelBuilder.Entity("TP4SCS.Library.Models.Data.SubscriptionPack", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Period")
                        .HasColumnType("int");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("Id")
                        .HasName("PK__Subscrip__3214EC0768CEF925");

                    b.HasIndex(new[] { "Name" }, "UQ__Subscrip__737584F6DC09C378")
                        .IsUnique();

                    b.ToTable("SubscriptionPack", (string)null);
                });

            modelBuilder.Entity("TP4SCS.Library.Models.Data.SupportTicket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__SupportT__3214EC072BE152EF");

                    b.HasIndex("AccountId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("OrderId");

                    b.ToTable("SupportTicket", (string)null);
                });

            modelBuilder.Entity("TP4SCS.Library.Models.Data.TicketCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__TicketCa__3214EC07223ACD26");

                    b.HasIndex(new[] { "Name" }, "UQ__TicketCa__737584F61AF30862")
                        .IsUnique();

                    b.ToTable("TicketCategory", (string)null);
                });

            modelBuilder.Entity("TP4SCS.Library.Models.Data.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MethodId")
                        .HasColumnType("int");

                    b.Property<int>("PackId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ProcessTime")
                        .HasColumnType("datetime");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__Transact__3214EC07CBA7DAF8");

                    b.HasIndex("AccountId");

                    b.HasIndex("MethodId");

                    b.HasIndex("PackId");

                    b.ToTable("Transaction", (string)null);
                });

            modelBuilder.Entity("TP4SCS.Library.Models.Data.AccountAddress", b =>
                {
                    b.HasOne("TP4SCS.Library.Models.Data.Account", "Account")
                        .WithMany("AccountAddresses")
                        .HasForeignKey("AccountId")
                        .IsRequired()
                        .HasConstraintName("FK__AccountAd__Accou__534D60F1");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("TP4SCS.Library.Models.Data.AssetUrl", b =>
                {
                    b.HasOne("TP4SCS.Library.Models.Data.BusinessProfile", "Business")
                        .WithMany("AssetUrls")
                        .HasForeignKey("BusinessId")
                        .HasConstraintName("FK__AssetURL__Busine__0C85DE4D");

                    b.HasOne("TP4SCS.Library.Models.Data.Feedback", "Feedback")
                        .WithMany("AssetUrls")
                        .HasForeignKey("FeedbackId")
                        .HasConstraintName("FK__AssetURL__Feedba__0D7A0286");

                    b.HasOne("TP4SCS.Library.Models.Data.Service", "Service")
                        .WithMany("AssetUrls")
                        .HasForeignKey("ServiceId")
                        .HasConstraintName("FK__AssetURL__Servic__0E6E26BF");

                    b.Navigation("Business");

                    b.Navigation("Feedback");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("TP4SCS.Library.Models.Data.BusinessBranch", b =>
                {
                    b.HasOne("TP4SCS.Library.Models.Data.BusinessProfile", "Business")
                        .WithMany("BusinessBranches")
                        .HasForeignKey("BusinessId")
                        .IsRequired()
                        .HasConstraintName("FK__BusinessB__Busin__5DCAEF64");

                    b.Navigation("Business");
                });

            modelBuilder.Entity("TP4SCS.Library.Models.Data.BusinessProfile", b =>
                {
                    b.HasOne("TP4SCS.Library.Models.Data.Account", "Owner")
                        .WithOne("BusinessProfile")
                        .HasForeignKey("TP4SCS.Library.Models.Data.BusinessProfile", "OwnerId")
                        .IsRequired()
                        .HasConstraintName("FK__BusinessP__Owner__59FA5E80");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("TP4SCS.Library.Models.Data.Cart", b =>
                {
                    b.HasOne("TP4SCS.Library.Models.Data.Account", "Account")
                        .WithOne("Cart")
                        .HasForeignKey("TP4SCS.Library.Models.Data.Cart", "AccountId")
                        .IsRequired()
                        .HasConstraintName("FK__Cart__AccountId__75A278F5");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("TP4SCS.Library.Models.Data.CartItem", b =>
                {
                    b.HasOne("TP4SCS.Library.Models.Data.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .IsRequired()
                        .HasConstraintName("FK__CartItem__CartId__787EE5A0");

                    b.HasOne("TP4SCS.Library.Models.Data.Material", "Material")
                        .WithMany("CartItems")
                        .HasForeignKey("MaterialId")
                        .HasConstraintName("FK__CartItem__Materi__7A672E12");

                    b.HasOne("TP4SCS.Library.Models.Data.Service", "Service")
                        .WithMany("CartItems")
                        .HasForeignKey("ServiceId")
                        .IsRequired()
                        .HasConstraintName("FK__CartItem__Servic__797309D9");

                    b.Navigation("Cart");

                    b.Navigation("Material");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("TP4SCS.Library.Models.Data.Feedback", b =>
                {
                    b.HasOne("TP4SCS.Library.Models.Data.OrderDetail", "OrderItem")
                        .WithMany("Feedbacks")
                        .HasForeignKey("OrderItemId")
                        .IsRequired()
                        .HasConstraintName("FK__Feedback__OrderI__07C12930");

                    b.Navigation("OrderItem");
                });

            modelBuilder.Entity("TP4SCS.Library.Models.Data.Order", b =>
                {
                    b.HasOne("TP4SCS.Library.Models.Data.Account", "Account")
                        .WithMany("Orders")
                        .HasForeignKey("AccountId")
                        .IsRequired()
                        .HasConstraintName("FK__Order__AccountId__7E37BEF6");

                    b.HasOne("TP4SCS.Library.Models.Data.AccountAddress", "Address")
                        .WithMany("Orders")
                        .HasForeignKey("AddressId")
                        .HasConstraintName("FK__Order__AddressId__7F2BE32F");

                    b.Navigation("Account");

                    b.Navigation("Address");
                });

            modelBuilder.Entity("TP4SCS.Library.Models.Data.OrderDetail", b =>
                {
                    b.HasOne("TP4SCS.Library.Models.Data.Material", "Material")
                        .WithMany("OrderDetails")
                        .HasForeignKey("MaterialId")
                        .HasConstraintName("FK__OrderDeta__Mater__04E4BC85");

                    b.HasOne("TP4SCS.Library.Models.Data.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .IsRequired()
                        .HasConstraintName("FK__OrderDeta__Order__02FC7413");

                    b.HasOne("TP4SCS.Library.Models.Data.Service", "Service")
                        .WithMany("OrderDetails")
                        .HasForeignKey("ServiceId")
                        .IsRequired()
                        .HasConstraintName("FK__OrderDeta__Servi__03F0984C");

                    b.Navigation("Material");

                    b.Navigation("Order");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("TP4SCS.Library.Models.Data.OrderNotification", b =>
                {
                    b.HasOne("TP4SCS.Library.Models.Data.Order", "Order")
                        .WithMany("OrderNotifications")
                        .HasForeignKey("OrderId")
                        .IsRequired()
                        .HasConstraintName("FK__OrderNoti__Order__1CBC4616");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("TP4SCS.Library.Models.Data.Promotion", b =>
                {
                    b.HasOne("TP4SCS.Library.Models.Data.Service", "Service")
                        .WithOne("Promotion")
                        .HasForeignKey("TP4SCS.Library.Models.Data.Promotion", "ServiceId")
                        .IsRequired()
                        .HasConstraintName("FK__Promotion__Servi__71D1E811");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("TP4SCS.Library.Models.Data.Service", b =>
                {
                    b.HasOne("TP4SCS.Library.Models.Data.BusinessBranch", "Branch")
                        .WithMany("Services")
                        .HasForeignKey("BranchId")
                        .IsRequired()
                        .HasConstraintName("FK__Service__BranchI__66603565");

                    b.HasOne("TP4SCS.Library.Models.Data.ServiceCategory", "Category")
                        .WithMany("Services")
                        .HasForeignKey("CategoryId")
                        .IsRequired()
                        .HasConstraintName("FK__Service__Categor__656C112C");

                    b.Navigation("Branch");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("TP4SCS.Library.Models.Data.ServiceMaterial", b =>
                {
                    b.HasOne("TP4SCS.Library.Models.Data.Material", "Material")
                        .WithMany("ServiceMaterials")
                        .HasForeignKey("MaterialId")
                        .HasConstraintName("FK__ServiceMa__Mater__6D0D32F4");

                    b.HasOne("TP4SCS.Library.Models.Data.Service", "Service")
                        .WithMany("ServiceMaterials")
                        .HasForeignKey("ServiceId")
                        .IsRequired()
                        .HasConstraintName("FK__ServiceMa__Servi__6C190EBB");

                    b.Navigation("Material");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("TP4SCS.Library.Models.Data.SupportTicket", b =>
                {
                    b.HasOne("TP4SCS.Library.Models.Data.Account", "Account")
                        .WithMany("SupportTickets")
                        .HasForeignKey("AccountId")
                        .IsRequired()
                        .HasConstraintName("FK__SupportTi__Accou__245D67DE");

                    b.HasOne("TP4SCS.Library.Models.Data.TicketCategory", "Category")
                        .WithMany("SupportTickets")
                        .HasForeignKey("CategoryId")
                        .IsRequired()
                        .HasConstraintName("FK__SupportTi__Categ__25518C17");

                    b.HasOne("TP4SCS.Library.Models.Data.Order", "Order")
                        .WithMany("SupportTickets")
                        .HasForeignKey("OrderId")
                        .HasConstraintName("FK__SupportTi__Order__2645B050");

                    b.Navigation("Account");

                    b.Navigation("Category");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("TP4SCS.Library.Models.Data.Transaction", b =>
                {
                    b.HasOne("TP4SCS.Library.Models.Data.Account", "Account")
                        .WithMany("Transactions")
                        .HasForeignKey("AccountId")
                        .IsRequired()
                        .HasConstraintName("FK__Transacti__Accou__17F790F9");

                    b.HasOne("TP4SCS.Library.Models.Data.PaymentMethod", "Method")
                        .WithMany("Transactions")
                        .HasForeignKey("MethodId")
                        .IsRequired()
                        .HasConstraintName("FK__Transacti__Metho__18EBB532");

                    b.HasOne("TP4SCS.Library.Models.Data.SubscriptionPack", "Pack")
                        .WithMany("Transactions")
                        .HasForeignKey("PackId")
                        .IsRequired()
                        .HasConstraintName("FK__Transacti__PackI__19DFD96B");

                    b.Navigation("Account");

                    b.Navigation("Method");

                    b.Navigation("Pack");
                });

            modelBuilder.Entity("TP4SCS.Library.Models.Data.Account", b =>
                {
                    b.Navigation("AccountAddresses");

                    b.Navigation("BusinessProfile");

                    b.Navigation("Cart");

                    b.Navigation("Orders");

                    b.Navigation("SupportTickets");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("TP4SCS.Library.Models.Data.AccountAddress", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("TP4SCS.Library.Models.Data.BusinessBranch", b =>
                {
                    b.Navigation("Services");
                });

            modelBuilder.Entity("TP4SCS.Library.Models.Data.BusinessProfile", b =>
                {
                    b.Navigation("AssetUrls");

                    b.Navigation("BusinessBranches");
                });

            modelBuilder.Entity("TP4SCS.Library.Models.Data.Cart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("TP4SCS.Library.Models.Data.Feedback", b =>
                {
                    b.Navigation("AssetUrls");
                });

            modelBuilder.Entity("TP4SCS.Library.Models.Data.Material", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("OrderDetails");

                    b.Navigation("ServiceMaterials");
                });

            modelBuilder.Entity("TP4SCS.Library.Models.Data.Order", b =>
                {
                    b.Navigation("OrderDetails");

                    b.Navigation("OrderNotifications");

                    b.Navigation("SupportTickets");
                });

            modelBuilder.Entity("TP4SCS.Library.Models.Data.OrderDetail", b =>
                {
                    b.Navigation("Feedbacks");
                });

            modelBuilder.Entity("TP4SCS.Library.Models.Data.PaymentMethod", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("TP4SCS.Library.Models.Data.Service", b =>
                {
                    b.Navigation("AssetUrls");

                    b.Navigation("CartItems");

                    b.Navigation("OrderDetails");

                    b.Navigation("Promotion");

                    b.Navigation("ServiceMaterials");
                });

            modelBuilder.Entity("TP4SCS.Library.Models.Data.ServiceCategory", b =>
                {
                    b.Navigation("Services");
                });

            modelBuilder.Entity("TP4SCS.Library.Models.Data.SubscriptionPack", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("TP4SCS.Library.Models.Data.TicketCategory", b =>
                {
                    b.Navigation("SupportTickets");
                });
#pragma warning restore 612, 618
        }
    }
}
