// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TP4SCS.Library.Models.Data;

#nullable disable

namespace TP4SCS.Library.Migrations
{
    [DbContext(typeof(Tp4scsDevDatabaseContext))]
    [Migration("20241010075641_Update-Service-and-Category-Model")]
    partial class UpdateServiceandCategoryModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TP4SCS.Library.Models.Data.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Dob")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("ExpiredTime")
                        .HasColumnType("datetime");

                    b.Property<string>("Fcmtoken")
                        .HasColumnType("text")
                        .HasColumnName("FCMTOKEN");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsGoogle")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__Account__3214EC07B6815457");

                    b.HasIndex(new[] { "Phone" }, "UQ__Account__5C7E359EF930D97A")
                        .IsUnique();

                    b.HasIndex(new[] { "Email" }, "UQ__Account__A9D10534C97D4C51")
                        .IsUnique();

                    b.ToTable("Account", (string)null);
                });

            modelBuilder.Entity("TP4SCS.Library.Models.Data.AccountAddress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Ward")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__AccountA__3214EC07277C1827");

                    b.HasIndex("AccountId");

                    b.ToTable("AccountAddress", (string)null);
                });

            modelBuilder.Entity("TP4SCS.Library.Models.Data.AssetUrl", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BusinessProfileId")
                        .HasColumnType("int");

                    b.Property<int?>("FeedbackId")
                        .HasColumnType("int");

                    b.Property<int?>("ServiceId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id")
                        .HasName("PK__AssetURL__3214EC073B92038A");

                    b.HasIndex("BusinessProfileId");

                    b.HasIndex("FeedbackId");

                    b.HasIndex("ServiceId");

                    b.ToTable("AssetURL", (string)null);
                });

            modelBuilder.Entity("TP4SCS.Library.Models.Data.BusinessBranch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("CategoryManagerIds")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EmployeeManagerIds")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("OrderManagerIds")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ServiceManagerIds")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Ward")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__Business__3214EC077BDBEDF6");

                    b.HasIndex("OwnerId");

                    b.ToTable("BusinessBranch", (string)null);
                });

            modelBuilder.Entity("TP4SCS.Library.Models.Data.BusinessProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ExpireTime")
                        .HasColumnType("datetime");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<decimal>("Rating")
                        .HasColumnType("decimal(3, 1)");

                    b.Property<DateTime>("RegisterTime")
                        .HasColumnType("datetime");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("TotalOrder")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Business__3214EC079E653ED5");

                    b.HasIndex("OwnerId");

                    b.HasIndex(new[] { "Phone" }, "UQ__Business__5C7E359EDD9E92F2")
                        .IsUnique();

                    b.HasIndex(new[] { "Name" }, "UQ__Business__737584F6B46B45DC")
                        .IsUnique();

                    b.ToTable("BusinessProfile", (string)null);
                });

            modelBuilder.Entity("TP4SCS.Library.Models.Data.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("Id")
                        .HasName("PK__Cart__3214EC073F946AF1");

                    b.HasIndex("AccountId");

                    b.ToTable("Cart", (string)null);
                });

            modelBuilder.Entity("TP4SCS.Library.Models.Data.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__CartItem__3214EC07AC82DD49");

                    b.HasIndex("CartId");

                    b.HasIndex("ServiceId");

                    b.ToTable("CartItem", (string)null);
                });

            modelBuilder.Entity("TP4SCS.Library.Models.Data.Feedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<int>("OrderItemId")
                        .HasColumnType("int");

                    b.Property<decimal>("Rating")
                        .HasColumnType("decimal(3, 1)");

                    b.HasKey("Id")
                        .HasName("PK__Feedback__3214EC07886BA30E");

                    b.HasIndex("OrderItemId");

                    b.ToTable("Feedback", (string)null);
                });

            modelBuilder.Entity("TP4SCS.Library.Models.Data.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DeliveredTime")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsAutoReject")
                        .HasColumnType("bit");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<decimal>("OrderPrice")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal>("ShipFee")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("ShippingCode")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ShippingUnit")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("Id")
                        .HasName("PK__Order__3214EC074072D21E");

                    b.HasIndex("AccountId");

                    b.ToTable("Order", (string)null);
                });

            modelBuilder.Entity("TP4SCS.Library.Models.Data.OrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__OrderDet__3214EC073D488B38");

                    b.HasIndex("OrderId");

                    b.HasIndex("ServiceId");

                    b.ToTable("OrderDetail", (string)null);
                });

            modelBuilder.Entity("TP4SCS.Library.Models.Data.OrderNotification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("NotificationTime")
                        .HasColumnType("datetime");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__OrderNot__3214EC07DFBB7E11");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderNotification", (string)null);
                });

            modelBuilder.Entity("TP4SCS.Library.Models.Data.PaymentMethod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id")
                        .HasName("PK__PaymentM__3214EC07DA914CF8");

                    b.ToTable("PaymentMethod", (string)null);
                });

            modelBuilder.Entity("TP4SCS.Library.Models.Data.Promotion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime");

                    b.Property<int>("SaleOff")
                        .HasColumnType("int");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Usage")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Promotio__3214EC07114711A7");

                    b.HasIndex("ServiceId");

                    b.ToTable("Promotion", (string)null);
                });

            modelBuilder.Entity("TP4SCS.Library.Models.Data.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("FeedbackedNum")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("OrderedNum")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal>("Rating")
                        .HasColumnType("decimal(3, 1)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__Service__3214EC07C115A187");

                    b.HasIndex("BranchId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Service", (string)null);
                });

            modelBuilder.Entity("TP4SCS.Library.Models.Data.ServiceCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id")
                        .HasName("PK__ServiceC__3214EC07AD3F9285");

                    b.ToTable("ServiceCategory", (string)null);
                });

            modelBuilder.Entity("TP4SCS.Library.Models.Data.SubscriptionPack", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Period")
                        .HasColumnType("int");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("Id")
                        .HasName("PK__Subscrip__3214EC0759802449");

                    b.ToTable("SubscriptionPack", (string)null);
                });

            modelBuilder.Entity("TP4SCS.Library.Models.Data.SupportTicket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__SupportT__3214EC07304B71CA");

                    b.HasIndex("AccountId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("OrderId");

                    b.ToTable("SupportTicket", (string)null);
                });

            modelBuilder.Entity("TP4SCS.Library.Models.Data.TicketCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id")
                        .HasName("PK__TicketCa__3214EC07B10E6832");

                    b.ToTable("TicketCategory", (string)null);
                });

            modelBuilder.Entity("TP4SCS.Library.Models.Data.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("MethodId")
                        .HasColumnType("int");

                    b.Property<int?>("PackId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ProcessTime")
                        .HasColumnType("datetime");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__Transact__3214EC075FD4B549");

                    b.HasIndex("AccountId");

                    b.HasIndex("MethodId");

                    b.HasIndex("PackId");

                    b.ToTable("Transaction", (string)null);
                });

            modelBuilder.Entity("TP4SCS.Library.Models.Data.AccountAddress", b =>
                {
                    b.HasOne("TP4SCS.Library.Models.Data.Account", "Account")
                        .WithMany("AccountAddresses")
                        .HasForeignKey("AccountId")
                        .IsRequired()
                        .HasConstraintName("FK__AccountAd__Accou__71D1E811");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("TP4SCS.Library.Models.Data.AssetUrl", b =>
                {
                    b.HasOne("TP4SCS.Library.Models.Data.BusinessProfile", "BusinessProfile")
                        .WithMany("AssetUrls")
                        .HasForeignKey("BusinessProfileId")
                        .HasConstraintName("FK__AssetURL__Busine__6D0D32F4");

                    b.HasOne("TP4SCS.Library.Models.Data.Feedback", "Feedback")
                        .WithMany("AssetUrls")
                        .HasForeignKey("FeedbackId")
                        .HasConstraintName("FK__AssetURL__Feedba__6E01572D");

                    b.HasOne("TP4SCS.Library.Models.Data.Service", "Service")
                        .WithMany("AssetUrls")
                        .HasForeignKey("ServiceId")
                        .HasConstraintName("FK__AssetURL__Servic__6EF57B66");

                    b.Navigation("BusinessProfile");

                    b.Navigation("Feedback");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("TP4SCS.Library.Models.Data.BusinessBranch", b =>
                {
                    b.HasOne("TP4SCS.Library.Models.Data.Account", "Owner")
                        .WithMany("BusinessBranches")
                        .HasForeignKey("OwnerId")
                        .IsRequired()
                        .HasConstraintName("FK__BusinessB__Owner__4D94879B");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("TP4SCS.Library.Models.Data.BusinessProfile", b =>
                {
                    b.HasOne("TP4SCS.Library.Models.Data.Account", "Owner")
                        .WithMany("BusinessProfiles")
                        .HasForeignKey("OwnerId")
                        .IsRequired()
                        .HasConstraintName("FK__BusinessP__Owner__60A75C0F");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("TP4SCS.Library.Models.Data.Cart", b =>
                {
                    b.HasOne("TP4SCS.Library.Models.Data.Account", "Account")
                        .WithMany("Carts")
                        .HasForeignKey("AccountId")
                        .IsRequired()
                        .HasConstraintName("FK__Cart__AccountId__5812160E");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("TP4SCS.Library.Models.Data.CartItem", b =>
                {
                    b.HasOne("TP4SCS.Library.Models.Data.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .IsRequired()
                        .HasConstraintName("FK__CartItem__CartId__5AEE82B9");

                    b.HasOne("TP4SCS.Library.Models.Data.Service", "Service")
                        .WithMany("CartItems")
                        .HasForeignKey("ServiceId")
                        .IsRequired()
                        .HasConstraintName("FK__CartItem__Servic__5BE2A6F2");

                    b.Navigation("Cart");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("TP4SCS.Library.Models.Data.Feedback", b =>
                {
                    b.HasOne("TP4SCS.Library.Models.Data.OrderDetail", "OrderItem")
                        .WithMany("Feedbacks")
                        .HasForeignKey("OrderItemId")
                        .IsRequired()
                        .HasConstraintName("FK__Feedback__OrderI__6A30C649");

                    b.Navigation("OrderItem");
                });

            modelBuilder.Entity("TP4SCS.Library.Models.Data.Order", b =>
                {
                    b.HasOne("TP4SCS.Library.Models.Data.Account", "Account")
                        .WithMany("Orders")
                        .HasForeignKey("AccountId")
                        .IsRequired()
                        .HasConstraintName("FK__Order__AccountId__6383C8BA");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("TP4SCS.Library.Models.Data.OrderDetail", b =>
                {
                    b.HasOne("TP4SCS.Library.Models.Data.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .IsRequired()
                        .HasConstraintName("FK__OrderDeta__Order__66603565");

                    b.HasOne("TP4SCS.Library.Models.Data.Service", "Service")
                        .WithMany("OrderDetails")
                        .HasForeignKey("ServiceId")
                        .IsRequired()
                        .HasConstraintName("FK__OrderDeta__Servi__6754599E");

                    b.Navigation("Order");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("TP4SCS.Library.Models.Data.OrderNotification", b =>
                {
                    b.HasOne("TP4SCS.Library.Models.Data.Order", "Order")
                        .WithMany("OrderNotifications")
                        .HasForeignKey("OrderId")
                        .IsRequired()
                        .HasConstraintName("FK__OrderNoti__Order__7D439ABD");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("TP4SCS.Library.Models.Data.Promotion", b =>
                {
                    b.HasOne("TP4SCS.Library.Models.Data.Service", "Service")
                        .WithMany("Promotions")
                        .HasForeignKey("ServiceId")
                        .IsRequired()
                        .HasConstraintName("FK__Promotion__Servi__534D60F1");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("TP4SCS.Library.Models.Data.Service", b =>
                {
                    b.HasOne("TP4SCS.Library.Models.Data.BusinessBranch", "Branch")
                        .WithMany("Services")
                        .HasForeignKey("BranchId")
                        .IsRequired()
                        .HasConstraintName("FK__Service__BranchI__5070F446");

                    b.HasOne("TP4SCS.Library.Models.Data.ServiceCategory", "ServiceCategory")
                        .WithMany("Services")
                        .HasForeignKey("CategoryId")
                        .IsRequired()
                        .HasConstraintName("FK__Service__Category__6112A204");

                    b.Navigation("Branch");

                    b.Navigation("ServiceCategory");
                });

            modelBuilder.Entity("TP4SCS.Library.Models.Data.SupportTicket", b =>
                {
                    b.HasOne("TP4SCS.Library.Models.Data.Account", "Account")
                        .WithMany("SupportTickets")
                        .HasForeignKey("AccountId")
                        .IsRequired()
                        .HasConstraintName("FK__SupportTi__Accou__02084FDA");

                    b.HasOne("TP4SCS.Library.Models.Data.TicketCategory", "Category")
                        .WithMany("SupportTickets")
                        .HasForeignKey("CategoryId")
                        .IsRequired()
                        .HasConstraintName("FK__SupportTi__Categ__02FC7413");

                    b.HasOne("TP4SCS.Library.Models.Data.Order", "Order")
                        .WithMany("SupportTickets")
                        .HasForeignKey("OrderId")
                        .HasConstraintName("FK__SupportTi__Order__03F0984C");

                    b.Navigation("Account");

                    b.Navigation("Category");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("TP4SCS.Library.Models.Data.Transaction", b =>
                {
                    b.HasOne("TP4SCS.Library.Models.Data.Account", "Account")
                        .WithMany("Transactions")
                        .HasForeignKey("AccountId")
                        .IsRequired()
                        .HasConstraintName("FK__Transacti__Accou__787EE5A0");

                    b.HasOne("TP4SCS.Library.Models.Data.PaymentMethod", "Method")
                        .WithMany("Transactions")
                        .HasForeignKey("MethodId")
                        .IsRequired()
                        .HasConstraintName("FK__Transacti__Metho__797309D9");

                    b.HasOne("TP4SCS.Library.Models.Data.SubscriptionPack", "Pack")
                        .WithMany("Transactions")
                        .HasForeignKey("PackId")
                        .HasConstraintName("FK__Transacti__PackI__7A672E12");

                    b.Navigation("Account");

                    b.Navigation("Method");

                    b.Navigation("Pack");
                });

            modelBuilder.Entity("TP4SCS.Library.Models.Data.Account", b =>
                {
                    b.Navigation("AccountAddresses");

                    b.Navigation("BusinessBranches");

                    b.Navigation("BusinessProfiles");

                    b.Navigation("Carts");

                    b.Navigation("Orders");

                    b.Navigation("SupportTickets");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("TP4SCS.Library.Models.Data.BusinessBranch", b =>
                {
                    b.Navigation("Services");
                });

            modelBuilder.Entity("TP4SCS.Library.Models.Data.BusinessProfile", b =>
                {
                    b.Navigation("AssetUrls");
                });

            modelBuilder.Entity("TP4SCS.Library.Models.Data.Cart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("TP4SCS.Library.Models.Data.Feedback", b =>
                {
                    b.Navigation("AssetUrls");
                });

            modelBuilder.Entity("TP4SCS.Library.Models.Data.Order", b =>
                {
                    b.Navigation("OrderDetails");

                    b.Navigation("OrderNotifications");

                    b.Navigation("SupportTickets");
                });

            modelBuilder.Entity("TP4SCS.Library.Models.Data.OrderDetail", b =>
                {
                    b.Navigation("Feedbacks");
                });

            modelBuilder.Entity("TP4SCS.Library.Models.Data.PaymentMethod", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("TP4SCS.Library.Models.Data.Service", b =>
                {
                    b.Navigation("AssetUrls");

                    b.Navigation("CartItems");

                    b.Navigation("OrderDetails");

                    b.Navigation("Promotions");
                });

            modelBuilder.Entity("TP4SCS.Library.Models.Data.ServiceCategory", b =>
                {
                    b.Navigation("Services");
                });

            modelBuilder.Entity("TP4SCS.Library.Models.Data.SubscriptionPack", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("TP4SCS.Library.Models.Data.TicketCategory", b =>
                {
                    b.Navigation("SupportTickets");
                });
#pragma warning restore 612, 618
        }
    }
}
