// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TP4SCS.Library.Models.Data;

#nullable disable

namespace TP4SCS.Library.Migrations
{
    [DbContext(typeof(Tp4scsDevDatabaseContext))]
    partial class Tp4scsDevDatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TP4SCS.Library.Models.Data.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedByOwnerId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Dob")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Fcmtoken")
                        .HasColumnType("text")
                        .HasColumnName("FCMToken");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsGoogle")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime?>("RefreshExpireTime")
                        .HasColumnType("datetime");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.HasKey("Id")
                        .HasName("PK__Account__3214EC073C1F4424");

                    b.HasIndex(new[] { "Phone" }, "UQ__Account__5C7E359ED0B30486")
                        .IsUnique();

                    b.HasIndex(new[] { "Email" }, "UQ__Account__A9D105341B4EBE88")
                        .IsUnique();

                    b.ToTable("Account", (string)null);
                });

            modelBuilder.Entity("TP4SCS.Library.Models.Data.AccountAddress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("Ward")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__AccountA__3214EC07902AF138");

                    b.HasIndex("AccountId");

                    b.ToTable("AccountAddress", (string)null);
                });

            modelBuilder.Entity("TP4SCS.Library.Models.Data.AssetUrl", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BusinessId")
                        .HasColumnType("int");

                    b.Property<int?>("FeedbackId")
                        .HasColumnType("int");

                    b.Property<bool>("IsImage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int?>("MaterialId")
                        .HasColumnType("int");

                    b.Property<int?>("ServiceId")
                        .HasColumnType("int");

                    b.Property<int?>("TicketId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id")
                        .HasName("PK__AssetURL__3214EC0720682CC0");

                    b.HasIndex("BusinessId");

                    b.HasIndex("FeedbackId");

                    b.HasIndex("MaterialId");

                    b.HasIndex("ServiceId");

                    b.HasIndex("TicketId");

                    b.ToTable("AssetURL", (string)null);
                });

            modelBuilder.Entity("TP4SCS.Library.Models.Data.BranchMaterial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<int>("MaterialId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<int>("Storage")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__BranchMa__3214EC0725A2F9B1");

                    b.HasIndex("BranchId");

                    b.HasIndex("MaterialId");

                    b.ToTable("BranchMaterial", (string)null);
                });

            modelBuilder.Entity("TP4SCS.Library.Models.Data.BranchService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.HasKey("Id")
                        .HasName("PK__BranchSe__3214EC07FB12F090");

                    b.HasIndex("BranchId");

                    b.HasIndex("ServiceId");

                    b.ToTable("BranchService", (string)null);
                });

            modelBuilder.Entity("TP4SCS.Library.Models.Data.BusinessBranch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("BusinessId")
                        .HasColumnType("int");

                    b.Property<int>("CanceledAmount")
                        .HasColumnType("int");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EmployeeIds")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("FinishedAmount")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeliverySupport")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PendingAmount")
                        .HasColumnType("int");

                    b.Property<int>("ProcessingAmount")
                        .HasColumnType("int");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Ward")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__Business__3214EC07490CABDE");

                    b.HasIndex("BusinessId");

                    b.ToTable("BusinessBranch", (string)null);
                });

            modelBuilder.Entity("TP4SCS.Library.Models.Data.BusinessProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CanceledAmount")
                        .HasColumnType("int");

                    b.Property<DateOnly>("CreatedDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("ExpiredTime")
                        .HasColumnType("datetime");

                    b.Property<int>("FinishedAmount")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.Property<int>("PendingAmount")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<int>("ProcessingAmount")
                        .HasColumnType("int");

                    b.Property<int>("Rank")
                        .HasColumnType("int");

                    b.Property<decimal>("Rating")
                        .HasColumnType("decimal(3, 1)");

                    b.Property<DateTime>("RegisteredTime")
                        .HasColumnType("datetime");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("ToTalServiceNum")
                        .HasColumnType("int");

                    b.Property<int>("TotalOrder")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Business__3214EC07ED8029A7");

                    b.HasIndex(new[] { "Phone" }, "UQ__Business__5C7E359E2849675E")
                        .IsUnique();

                    b.HasIndex(new[] { "Name" }, "UQ__Business__737584F6E9490AA2")
                        .IsUnique();

                    b.HasIndex(new[] { "OwnerId" }, "UQ__Business__819385B99918E945")
                        .IsUnique();

                    b.ToTable("BusinessProfile", (string)null);
                });

            modelBuilder.Entity("TP4SCS.Library.Models.Data.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("Id")
                        .HasName("PK__Cart__3214EC07DCFFAC04");

                    b.HasIndex(new[] { "AccountId" }, "UQ__Cart__349DA5A7385D22F1")
                        .IsUnique();

                    b.ToTable("Cart", (string)null);
                });

            modelBuilder.Entity("TP4SCS.Library.Models.Data.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<int?>("MaterialId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int?>("ServiceId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__CartItem__3214EC0761E88B0F");

                    b.HasIndex("BranchId");

                    b.HasIndex("CartId");

                    b.HasIndex("MaterialId");

                    b.HasIndex("ServiceId");

                    b.ToTable("CartItem", (string)null);
                });

            modelBuilder.Entity("TP4SCS.Library.Models.Data.Feedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsValidAsset")
                        .HasColumnType("bit");

                    b.Property<bool>("IsValidContent")
                        .HasColumnType("bit");

                    b.Property<int>("OrderItemId")
                        .HasColumnType("int");

                    b.Property<decimal>("Rating")
                        .HasColumnType("decimal(3, 1)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.HasKey("Id")
                        .HasName("PK__Feedback__3214EC07D56B8A8F");

                    b.HasIndex("OrderItemId");

                    b.ToTable("Feedback", (string)null);
                });

            modelBuilder.Entity("TP4SCS.Library.Models.Data.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.HasKey("Id")
                        .HasName("PK__Material__3214EC0734365102");

                    b.ToTable("Material", (string)null);
                });

            modelBuilder.Entity("TP4SCS.Library.Models.Data.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<int?>("AddressId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime");

                    b.Property<decimal>("DeliveredFee")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<DateTime?>("DeliveredTime")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsAutoReject")
                        .HasColumnType("bit");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("OrderPrice")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("ShippingCode")
                        .HasColumnType("text");

                    b.Property<string>("ShippingUnit")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("Id")
                        .HasName("PK__Order__3214EC078F995ABA");

                    b.HasIndex("AccountId");

                    b.HasIndex("AddressId");

                    b.ToTable("Order", (string)null);
                });

            modelBuilder.Entity("TP4SCS.Library.Models.Data.OrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<int?>("MaterialId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int?>("ServiceId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.HasKey("Id")
                        .HasName("PK__OrderDet__3214EC07279BA547");

                    b.HasIndex("BranchId");

                    b.HasIndex("MaterialId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ServiceId");

                    b.ToTable("OrderDetail", (string)null);
                });

            modelBuilder.Entity("TP4SCS.Library.Models.Data.OrderNotification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NotificationTime")
                        .HasColumnType("datetime");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__OrderNot__3214EC07CCB007DE");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderNotification", (string)null);
                });

            modelBuilder.Entity("TP4SCS.Library.Models.Data.PaymentMethod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__PaymentM__3214EC07B807A74A");

                    b.HasIndex(new[] { "Name" }, "UQ__PaymentM__737584F60A4E9ADC")
                        .IsUnique();

                    b.ToTable("PaymentMethod", (string)null);
                });

            modelBuilder.Entity("TP4SCS.Library.Models.Data.Promotion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("NewPrice")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("SaleOff")
                        .HasColumnType("int");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.HasKey("Id")
                        .HasName("PK__Promotio__3214EC077627FC35");

                    b.HasIndex(new[] { "ServiceId" }, "UQ__Promotio__C51BB00BA6F917F4")
                        .IsUnique();

                    b.ToTable("Promotion", (string)null);
                });

            modelBuilder.Entity("TP4SCS.Library.Models.Data.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FeedbackedNum")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("OrderedNum")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal>("Rating")
                        .HasColumnType("decimal(3, 1)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.HasKey("Id")
                        .HasName("PK__Service__3214EC075D7864DB");

                    b.HasIndex("CategoryId");

                    b.ToTable("Service", (string)null);
                });

            modelBuilder.Entity("TP4SCS.Library.Models.Data.ServiceCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.HasKey("Id")
                        .HasName("PK__ServiceC__3214EC071BC884F0");

                    b.HasIndex(new[] { "Name" }, "UQ__ServiceC__737584F6BA249531")
                        .IsUnique();

                    b.ToTable("ServiceCategory", (string)null);
                });

            modelBuilder.Entity("TP4SCS.Library.Models.Data.ServiceMaterial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("MaterialId")
                        .HasColumnType("int");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__ServiceM__3214EC0738AF65BD");

                    b.HasIndex("MaterialId");

                    b.HasIndex("ServiceId");

                    b.ToTable("ServiceMaterial", (string)null);
                });

            modelBuilder.Entity("TP4SCS.Library.Models.Data.SubscriptionPack", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Period")
                        .HasColumnType("int");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("Id")
                        .HasName("PK__Subscrip__3214EC07DBE48616");

                    b.HasIndex(new[] { "Name" }, "UQ__Subscrip__737584F69A6E84CA")
                        .IsUnique();

                    b.ToTable("SubscriptionPack", (string)null);
                });

            modelBuilder.Entity("TP4SCS.Library.Models.Data.SupportTicket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsParentTicket")
                        .HasColumnType("bit");

                    b.Property<int?>("ModeratorId")
                        .HasColumnType("int");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<int?>("ParentTicketId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__SupportT__3214EC07322ADA54");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ModeratorId");

                    b.HasIndex("OrderId");

                    b.HasIndex("UserId");

                    b.ToTable("SupportTicket", (string)null);
                });

            modelBuilder.Entity("TP4SCS.Library.Models.Data.TicketCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.HasKey("Id")
                        .HasName("PK__TicketCa__3214EC07047DE21B");

                    b.HasIndex(new[] { "Name" }, "UQ__TicketCa__737584F6380765D9")
                        .IsUnique();

                    b.ToTable("TicketCategory", (string)null);
                });

            modelBuilder.Entity("TP4SCS.Library.Models.Data.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MethodId")
                        .HasColumnType("int");

                    b.Property<int>("PackId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ProcessTime")
                        .HasColumnType("datetime");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.HasKey("Id")
                        .HasName("PK__Transact__3214EC07C1A83701");

                    b.HasIndex("AccountId");

                    b.HasIndex("MethodId");

                    b.HasIndex("PackId");

                    b.ToTable("Transaction", (string)null);
                });

            modelBuilder.Entity("TP4SCS.Library.Models.Data.AccountAddress", b =>
                {
                    b.HasOne("TP4SCS.Library.Models.Data.Account", "Account")
                        .WithMany("AccountAddresses")
                        .HasForeignKey("AccountId")
                        .IsRequired()
                        .HasConstraintName("FK__AccountAd__Accou__412EB0B6");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("TP4SCS.Library.Models.Data.AssetUrl", b =>
                {
                    b.HasOne("TP4SCS.Library.Models.Data.BusinessProfile", "Business")
                        .WithMany("AssetUrls")
                        .HasForeignKey("BusinessId")
                        .HasConstraintName("FK__AssetURL__Busine__114A936A");

                    b.HasOne("TP4SCS.Library.Models.Data.Feedback", "Feedback")
                        .WithMany("AssetUrls")
                        .HasForeignKey("FeedbackId")
                        .HasConstraintName("FK__AssetURL__Feedba__123EB7A3");

                    b.HasOne("TP4SCS.Library.Models.Data.Material", "Material")
                        .WithMany("AssetUrls")
                        .HasForeignKey("MaterialId")
                        .HasConstraintName("FK__AssetURL__Materi__14270015");

                    b.HasOne("TP4SCS.Library.Models.Data.Service", "Service")
                        .WithMany("AssetUrls")
                        .HasForeignKey("ServiceId")
                        .HasConstraintName("FK__AssetURL__Servic__1332DBDC");

                    b.HasOne("TP4SCS.Library.Models.Data.SupportTicket", "Ticket")
                        .WithMany("AssetUrls")
                        .HasForeignKey("TicketId")
                        .HasConstraintName("FK__AssetURL__Ticket__151B244E");

                    b.Navigation("Business");

                    b.Navigation("Feedback");

                    b.Navigation("Material");

                    b.Navigation("Service");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("TP4SCS.Library.Models.Data.BranchMaterial", b =>
                {
                    b.HasOne("TP4SCS.Library.Models.Data.BusinessBranch", "Branch")
                        .WithMany("BranchMaterials")
                        .HasForeignKey("BranchId")
                        .IsRequired()
                        .HasConstraintName("FK__BranchMat__Branc__6383C8BA");

                    b.HasOne("TP4SCS.Library.Models.Data.Material", "Material")
                        .WithMany("BranchMaterials")
                        .HasForeignKey("MaterialId")
                        .IsRequired()
                        .HasConstraintName("FK__BranchMat__Mater__628FA481");

                    b.Navigation("Branch");

                    b.Navigation("Material");
                });

            modelBuilder.Entity("TP4SCS.Library.Models.Data.BranchService", b =>
                {
                    b.HasOne("TP4SCS.Library.Models.Data.BusinessBranch", "Branch")
                        .WithMany("BranchServices")
                        .HasForeignKey("BranchId")
                        .IsRequired()
                        .HasConstraintName("FK__BranchSer__Branc__5EBF139D");

                    b.HasOne("TP4SCS.Library.Models.Data.Service", "Service")
                        .WithMany("BranchServices")
                        .HasForeignKey("ServiceId")
                        .IsRequired()
                        .HasConstraintName("FK__BranchSer__Servi__5DCAEF64");

                    b.Navigation("Branch");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("TP4SCS.Library.Models.Data.BusinessBranch", b =>
                {
                    b.HasOne("TP4SCS.Library.Models.Data.BusinessProfile", "Business")
                        .WithMany("BusinessBranches")
                        .HasForeignKey("BusinessId")
                        .IsRequired()
                        .HasConstraintName("FK__BusinessB__Busin__4BAC3F29");

                    b.Navigation("Business");
                });

            modelBuilder.Entity("TP4SCS.Library.Models.Data.BusinessProfile", b =>
                {
                    b.HasOne("TP4SCS.Library.Models.Data.Account", "Owner")
                        .WithOne("BusinessProfile")
                        .HasForeignKey("TP4SCS.Library.Models.Data.BusinessProfile", "OwnerId")
                        .IsRequired()
                        .HasConstraintName("FK__BusinessP__Owner__47DBAE45");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("TP4SCS.Library.Models.Data.Cart", b =>
                {
                    b.HasOne("TP4SCS.Library.Models.Data.Account", "Account")
                        .WithOne("Cart")
                        .HasForeignKey("TP4SCS.Library.Models.Data.Cart", "AccountId")
                        .IsRequired()
                        .HasConstraintName("FK__Cart__AccountId__6C190EBB");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("TP4SCS.Library.Models.Data.CartItem", b =>
                {
                    b.HasOne("TP4SCS.Library.Models.Data.BusinessBranch", "Branch")
                        .WithMany("CartItems")
                        .HasForeignKey("BranchId")
                        .IsRequired()
                        .HasConstraintName("FK__CartItem__Branch__6FE99F9F");

                    b.HasOne("TP4SCS.Library.Models.Data.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .IsRequired()
                        .HasConstraintName("FK__CartItem__CartId__6EF57B66");

                    b.HasOne("TP4SCS.Library.Models.Data.Material", "Material")
                        .WithMany("CartItems")
                        .HasForeignKey("MaterialId")
                        .HasConstraintName("FK__CartItem__Materi__71D1E811");

                    b.HasOne("TP4SCS.Library.Models.Data.Service", "Service")
                        .WithMany("CartItems")
                        .HasForeignKey("ServiceId")
                        .HasConstraintName("FK__CartItem__Servic__70DDC3D8");

                    b.Navigation("Branch");

                    b.Navigation("Cart");

                    b.Navigation("Material");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("TP4SCS.Library.Models.Data.Feedback", b =>
                {
                    b.HasOne("TP4SCS.Library.Models.Data.OrderDetail", "OrderItem")
                        .WithMany("Feedbacks")
                        .HasForeignKey("OrderItemId")
                        .IsRequired()
                        .HasConstraintName("FK__Feedback__OrderI__01142BA1");

                    b.Navigation("OrderItem");
                });

            modelBuilder.Entity("TP4SCS.Library.Models.Data.Order", b =>
                {
                    b.HasOne("TP4SCS.Library.Models.Data.Account", "Account")
                        .WithMany("Orders")
                        .HasForeignKey("AccountId")
                        .IsRequired()
                        .HasConstraintName("FK__Order__AccountId__75A278F5");

                    b.HasOne("TP4SCS.Library.Models.Data.AccountAddress", "Address")
                        .WithMany("Orders")
                        .HasForeignKey("AddressId")
                        .HasConstraintName("FK__Order__AddressId__76969D2E");

                    b.Navigation("Account");

                    b.Navigation("Address");
                });

            modelBuilder.Entity("TP4SCS.Library.Models.Data.OrderDetail", b =>
                {
                    b.HasOne("TP4SCS.Library.Models.Data.BusinessBranch", "Branch")
                        .WithMany("OrderDetails")
                        .HasForeignKey("BranchId")
                        .IsRequired()
                        .HasConstraintName("FK__OrderDeta__Branc__7B5B524B");

                    b.HasOne("TP4SCS.Library.Models.Data.Material", "Material")
                        .WithMany("OrderDetails")
                        .HasForeignKey("MaterialId")
                        .HasConstraintName("FK__OrderDeta__Mater__7D439ABD");

                    b.HasOne("TP4SCS.Library.Models.Data.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .IsRequired()
                        .HasConstraintName("FK__OrderDeta__Order__7A672E12");

                    b.HasOne("TP4SCS.Library.Models.Data.Service", "Service")
                        .WithMany("OrderDetails")
                        .HasForeignKey("ServiceId")
                        .HasConstraintName("FK__OrderDeta__Servi__7C4F7684");

                    b.Navigation("Branch");

                    b.Navigation("Material");

                    b.Navigation("Order");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("TP4SCS.Library.Models.Data.OrderNotification", b =>
                {
                    b.HasOne("TP4SCS.Library.Models.Data.Order", "Order")
                        .WithMany("OrderNotifications")
                        .HasForeignKey("OrderId")
                        .IsRequired()
                        .HasConstraintName("FK__OrderNoti__Order__236943A5");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("TP4SCS.Library.Models.Data.Promotion", b =>
                {
                    b.HasOne("TP4SCS.Library.Models.Data.Service", "Service")
                        .WithOne("Promotion")
                        .HasForeignKey("TP4SCS.Library.Models.Data.Promotion", "ServiceId")
                        .IsRequired()
                        .HasConstraintName("FK__Promotion__Servi__68487DD7");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("TP4SCS.Library.Models.Data.Service", b =>
                {
                    b.HasOne("TP4SCS.Library.Models.Data.ServiceCategory", "Category")
                        .WithMany("Services")
                        .HasForeignKey("CategoryId")
                        .IsRequired()
                        .HasConstraintName("FK__Service__Categor__534D60F1");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("TP4SCS.Library.Models.Data.ServiceMaterial", b =>
                {
                    b.HasOne("TP4SCS.Library.Models.Data.Material", "Material")
                        .WithMany("ServiceMaterials")
                        .HasForeignKey("MaterialId")
                        .HasConstraintName("FK__ServiceMa__Mater__59FA5E80");

                    b.HasOne("TP4SCS.Library.Models.Data.Service", "Service")
                        .WithMany("ServiceMaterials")
                        .HasForeignKey("ServiceId")
                        .IsRequired()
                        .HasConstraintName("FK__ServiceMa__Servi__59063A47");

                    b.Navigation("Material");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("TP4SCS.Library.Models.Data.SupportTicket", b =>
                {
                    b.HasOne("TP4SCS.Library.Models.Data.TicketCategory", "Category")
                        .WithMany("SupportTickets")
                        .HasForeignKey("CategoryId")
                        .IsRequired()
                        .HasConstraintName("FK__SupportTi__Categ__0B91BA14");

                    b.HasOne("TP4SCS.Library.Models.Data.Account", "Moderator")
                        .WithMany("SupportTicketModerators")
                        .HasForeignKey("ModeratorId")
                        .HasConstraintName("FK__SupportTi__Moder__0A9D95DB");

                    b.HasOne("TP4SCS.Library.Models.Data.Order", "Order")
                        .WithMany("SupportTickets")
                        .HasForeignKey("OrderId")
                        .HasConstraintName("FK__SupportTi__Order__0C85DE4D");

                    b.HasOne("TP4SCS.Library.Models.Data.Account", "User")
                        .WithMany("SupportTicketUsers")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__SupportTi__UserI__09A971A2");

                    b.Navigation("Category");

                    b.Navigation("Moderator");

                    b.Navigation("Order");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TP4SCS.Library.Models.Data.Transaction", b =>
                {
                    b.HasOne("TP4SCS.Library.Models.Data.Account", "Account")
                        .WithMany("Transactions")
                        .HasForeignKey("AccountId")
                        .IsRequired()
                        .HasConstraintName("FK__Transacti__Accou__1EA48E88");

                    b.HasOne("TP4SCS.Library.Models.Data.PaymentMethod", "Method")
                        .WithMany("Transactions")
                        .HasForeignKey("MethodId")
                        .IsRequired()
                        .HasConstraintName("FK__Transacti__Metho__1F98B2C1");

                    b.HasOne("TP4SCS.Library.Models.Data.SubscriptionPack", "Pack")
                        .WithMany("Transactions")
                        .HasForeignKey("PackId")
                        .IsRequired()
                        .HasConstraintName("FK__Transacti__PackI__208CD6FA");

                    b.Navigation("Account");

                    b.Navigation("Method");

                    b.Navigation("Pack");
                });

            modelBuilder.Entity("TP4SCS.Library.Models.Data.Account", b =>
                {
                    b.Navigation("AccountAddresses");

                    b.Navigation("BusinessProfile");

                    b.Navigation("Cart");

                    b.Navigation("Orders");

                    b.Navigation("SupportTicketModerators");

                    b.Navigation("SupportTicketUsers");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("TP4SCS.Library.Models.Data.AccountAddress", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("TP4SCS.Library.Models.Data.BusinessBranch", b =>
                {
                    b.Navigation("BranchMaterials");

                    b.Navigation("BranchServices");

                    b.Navigation("CartItems");

                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("TP4SCS.Library.Models.Data.BusinessProfile", b =>
                {
                    b.Navigation("AssetUrls");

                    b.Navigation("BusinessBranches");
                });

            modelBuilder.Entity("TP4SCS.Library.Models.Data.Cart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("TP4SCS.Library.Models.Data.Feedback", b =>
                {
                    b.Navigation("AssetUrls");
                });

            modelBuilder.Entity("TP4SCS.Library.Models.Data.Material", b =>
                {
                    b.Navigation("AssetUrls");

                    b.Navigation("BranchMaterials");

                    b.Navigation("CartItems");

                    b.Navigation("OrderDetails");

                    b.Navigation("ServiceMaterials");
                });

            modelBuilder.Entity("TP4SCS.Library.Models.Data.Order", b =>
                {
                    b.Navigation("OrderDetails");

                    b.Navigation("OrderNotifications");

                    b.Navigation("SupportTickets");
                });

            modelBuilder.Entity("TP4SCS.Library.Models.Data.OrderDetail", b =>
                {
                    b.Navigation("Feedbacks");
                });

            modelBuilder.Entity("TP4SCS.Library.Models.Data.PaymentMethod", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("TP4SCS.Library.Models.Data.Service", b =>
                {
                    b.Navigation("AssetUrls");

                    b.Navigation("BranchServices");

                    b.Navigation("CartItems");

                    b.Navigation("OrderDetails");

                    b.Navigation("Promotion");

                    b.Navigation("ServiceMaterials");
                });

            modelBuilder.Entity("TP4SCS.Library.Models.Data.ServiceCategory", b =>
                {
                    b.Navigation("Services");
                });

            modelBuilder.Entity("TP4SCS.Library.Models.Data.SubscriptionPack", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("TP4SCS.Library.Models.Data.SupportTicket", b =>
                {
                    b.Navigation("AssetUrls");
                });

            modelBuilder.Entity("TP4SCS.Library.Models.Data.TicketCategory", b =>
                {
                    b.Navigation("SupportTickets");
                });
#pragma warning restore 612, 618
        }
    }
}
